-- ============================================================================
-- Grant Permissions for SVC_CURSOR_ROLE on AI_QUESTION_INSIGHTS Schema
-- ============================================================================
-- Purpose: Grant necessary privileges to SVC_CURSOR_ROLE for read/write access
-- to AI_QUESTION_INSIGHTS schema objects
-- ============================================================================

-- Execute these grants as ACCOUNTADMIN or a role with GRANT privileges

USE ROLE ACCOUNTADMIN;

-- Grant schema-level privileges
GRANT USAGE ON SCHEMA CURSOR_DB.AI_QUESTION_INSIGHTS TO ROLE SVC_CURSOR_ROLE;
GRANT CREATE TABLE ON SCHEMA CURSOR_DB.AI_QUESTION_INSIGHTS TO ROLE SVC_CURSOR_ROLE;
GRANT CREATE VIEW ON SCHEMA CURSOR_DB.AI_QUESTION_INSIGHTS TO ROLE SVC_CURSOR_ROLE;
GRANT CREATE PROCEDURE ON SCHEMA CURSOR_DB.AI_QUESTION_INSIGHTS TO ROLE SVC_CURSOR_ROLE;
GRANT CREATE FUNCTION ON SCHEMA CURSOR_DB.AI_QUESTION_INSIGHTS TO ROLE SVC_CURSOR_ROLE;

-- Grant table privileges
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE CURSOR_DB.AI_QUESTION_INSIGHTS.CORTEX_ANALYST_REQUEST_HISTORY TO ROLE SVC_CURSOR_ROLE;

-- Grant future privileges for any new objects created in the schema
GRANT SELECT ON FUTURE VIEWS IN SCHEMA CURSOR_DB.AI_QUESTION_INSIGHTS TO ROLE SVC_CURSOR_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CURSOR_DB.AI_QUESTION_INSIGHTS TO ROLE SVC_CURSOR_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA CURSOR_DB.AI_QUESTION_INSIGHTS TO ROLE SVC_CURSOR_ROLE;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA CURSOR_DB.AI_QUESTION_INSIGHTS TO ROLE SVC_CURSOR_ROLE;

-- Verify grants
SHOW GRANTS ON SCHEMA CURSOR_DB.AI_QUESTION_INSIGHTS;
SHOW GRANTS TO ROLE SVC_CURSOR_ROLE;



