-- ============================================================================
-- QUICK GRANTS - AI QUESTION INSIGHTS
-- ============================================================================
-- Copy and paste this, replacing <TARGET_ROLE> with your role name
-- Run as: ACCOUNTADMIN
-- ============================================================================

-- === STEP 1: REPLACE <TARGET_ROLE> WITH YOUR ACTUAL ROLE ===
-- Examples: ANALYST_ROLE, DATA_TEAM_ROLE, BI_ROLE, etc.

USE ROLE ACCOUNTADMIN;

-- === STEP 2: GRANT READ-ONLY ACCESS (MOST COMMON) ===

-- Database and schema access
GRANT USAGE ON DATABASE CURSOR_DB TO ROLE <TARGET_ROLE>;
GRANT USAGE ON SCHEMA CURSOR_DB.AI_QUESTION_INSIGHTS TO ROLE <TARGET_ROLE>;

-- Table and view access
GRANT SELECT ON TABLE CURSOR_DB.AI_QUESTION_INSIGHTS.CORTEX_ANALYST_REQUEST_HISTORY TO ROLE <TARGET_ROLE>;
GRANT SELECT ON ALL VIEWS IN SCHEMA CURSOR_DB.AI_QUESTION_INSIGHTS TO ROLE <TARGET_ROLE>;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA CURSOR_DB.AI_QUESTION_INSIGHTS TO ROLE <TARGET_ROLE>;

-- Procedure execution access
GRANT USAGE ON ALL PROCEDURES IN SCHEMA CURSOR_DB.AI_QUESTION_INSIGHTS TO ROLE <TARGET_ROLE>;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA CURSOR_DB.AI_QUESTION_INSIGHTS TO ROLE <TARGET_ROLE>;

-- Warehouse access (required to run queries)
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE <TARGET_ROLE>;

-- === STEP 3: VERIFY ===
SHOW GRANTS TO ROLE <TARGET_ROLE>;

-- === STEP 4: TEST (Optional) ===
USE ROLE <TARGET_ROLE>;
SELECT * FROM CURSOR_DB.AI_QUESTION_INSIGHTS.VW_RECENT_REQUESTS LIMIT 5;
CALL CURSOR_DB.AI_QUESTION_INSIGHTS.GET_USER_QUESTION_PATTERNS(7, 10);

